version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - artifind-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=mongodb://mongo:27017/artifind
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongo
    networks:
      - artifind-network

  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: artifind-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: artifind2024
      MONGO_INITDB_DATABASE: artifind
    networks:
      - artifind-network

  # Redis for Caching (Optional)
  redis:
    image: redis:7.0-alpine
    container_name: artifind-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - artifind-network

  # Nginx Reverse Proxy (Production-ready)
  nginx:
    image: nginx:alpine
    container_name: artifind-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - artifind-network
    profiles:
      - production

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  artifind-network:
    driver: bridge